#### configuration

VERSION        = 3.16.1
NAME           = vimperator
UUID           = vimperator@boriselec.com
MIN_VERSION    = 28.0
MAX_VERSION    = *

-include private.properties

include ../common/Makefile
