#### configuration

VERSION        = 3.16.1
NAME           = vimperator
UUID           = vimperator@boriselec.com
MIN_VERSION    = 38.0
MAX_VERSION    = 51.0

-include private.properties

include ../common/Makefile
