#### configuration

VERSION        = 3.16.2
NAME           = vimperator
UUID           = vimperator@boriselec.com
MIN_VERSION    = 28.0
MAX_VERSION    = 33.*

-include private.properties

include ../common/Makefile
